name: playverse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Icons and Fonts and Requiered
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  flutter_advanced_drawer: ^1.3.5
  fluttertoast: ^8.2.4
  neopop: ^1.0.2

  #Firebase and Use
  firebase_core: ^2.21.0
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3
  firebase_auth: ^4.12.1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.0.1

  #Web Based
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  http: ^1.2.0
  provider: ^6.1.1
  intl: ^0.19.0
  file_picker: ^8.0.1
  video_player: ^2.8.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon/icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    # - assets/images/AuthImages/
    # - assets/images/loadingGifs/
    # - assets/images/GamesSample/
    # - assets/images/IconsSVG/
    # - assets/images/thumbnails/
    - assets/images/images/
    - assets/images/icon/
    - assets/images/gif/
 
  fonts:
    - family: GameOver
      fonts:
        - asset: assets/fonts/game_over.ttf
    - family: GamePaused
      fonts:
        - asset: assets/fonts/GamePaused.otf
    - family: PixelGaming
      fonts:
        - asset: assets/fonts/PixelGaming.ttf
    - family: UglyByte
      fonts:
        - asset: assets/fonts/UglyByte.otf
    - family: YujiBoku
      fonts:
        - asset: assets/fonts/YujiBoku-Regular.ttf