// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGtSnfZ07RpTcyAeNW3PdQD9OzD2x_mXI',
    appId: '1:639691401983:web:e8612ccebd98ab48743aca',
    messagingSenderId: '639691401983',
    projectId: 'trail1-86ba8',
    authDomain: 'trail1-86ba8.firebaseapp.com',
    storageBucket: 'trail1-86ba8.appspot.com',
    measurementId: 'G-BVVRREXM4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCExQHqfs37yvYcCEiiwsMJsrmhTMpIFs4',
    appId: '1:639691401983:android:bb1c76c1fee86019743aca',
    messagingSenderId: '639691401983',
    projectId: 'trail1-86ba8',
    storageBucket: 'trail1-86ba8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjMElE9f99QzRajKA9Q7_mPvXGblwp7Y',
    appId: '1:639691401983:ios:283aaf92717f1bf8743aca',
    messagingSenderId: '639691401983',
    projectId: 'trail1-86ba8',
    storageBucket: 'trail1-86ba8.appspot.com',
    androidClientId:
        '639691401983-700mgo0fn9b128hth0dfa7q8f1bpp3kt.apps.googleusercontent.com',
    iosClientId:
        '639691401983-kjmceltjef82ig3afrsolrujv8bk60id.apps.googleusercontent.com',
    iosBundleId: 'com.app.playverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjMElE9f99QzRajKA9Q7_mPvXGblwp7Y',
    appId: '1:639691401983:ios:c60f36a47b0750e8743aca',
    messagingSenderId: '639691401983',
    projectId: 'trail1-86ba8',
    storageBucket: 'trail1-86ba8.appspot.com',
    androidClientId:
        '639691401983-700mgo0fn9b128hth0dfa7q8f1bpp3kt.apps.googleusercontent.com',
    iosClientId:
        '639691401983-8odjogoegmvqpa3i9ga4nbsre7djd55e.apps.googleusercontent.com',
    iosBundleId: 'com.app.playverse.RunnerTests',
  );
}
